### ISSUE TITLE
Firmware Upgrade Fails

### ISSUE THREAD

**Issue by zamarax** [sophos-iaas/xg-azure#13]
Default instance from Azure deploys with MR1, upgrade to MR8 fails.

**Comment by jpwenzel** [comment]
Dear zamarax,

I'm sorry to hear that you're experiencing issues with our XG on Azure product.
Please be aware that you cannot reach out to our product support through this GitHub page.

I'll kindly ask you to contact our support team. Please provide them with more information about your installation so our specialists can help you fix your installation.
You'll find your options on how to get in touch with support on this website: https://www.sophos.com/en-us/support.aspx

Best,

--JP

**Comment by zamarax** [comment]
Apparently it's a known issue, can you update the Azure image to atleast MR8?

**Comment by jpwenzel** [comment]
Dear zamarax,

I am not aware of any "know issue" regarding your error description. Could you point me to the source of your statement?

As described in your other ticket, you should be able to upgrade to MR8 using the up2date mechanism from within the XG Control Center.

For further assistance, please contact your Sophos partner or the Sophos support organization:
https://www.sophos.com/en-us/support.aspx
