### ISSUE TITLE
Micro App Discovery HeadAches

### ISSUE THREAD

**Issue by zamarax** [sophos-iaas/xg-azure#14]
Micro App Discovery service in the MR1 release from Azure causes all types of connection drops which in turn cause other services on machines behind it to fail, such as loading ssl websites.

Disabling it in configuration files seems to resolve the issue and I understand in later released this service has been removed entirely.

**Comment by jpwenzel** [comment]
Dear zamarax,

I'm sorry to hear that you're experiencing issues with our XG on Azure product.
Please be aware that you cannot reach out to our product support through this GitHub page.

Please be aware that the most current version of XG on Azure is 16.05 MR8 (at the time of writing this): https://community.sophos.com/products/xg-firewall/b/xg-blog/posts/sfos-16-05-8-mr8-released.

Please make sure to upgrade to the latest version available as we're constantly improving product features with every release.

If you're still seeing this issue with the latest public version of XG, I'll kindly ask you to contact our support team. Please provide them with more information about your installation so our specialists can help you fix your installation.
You'll find your options on how to get in touch with support on this website: https://www.sophos.com/en-us/support.aspx

Best,

--JP

**Comment by zamarax** [comment]
That's not true, we just did deploy on Azure and MR1 is what gets deployed.

**Comment by jpwenzel** [comment]
Dear zamarax,

After launching XG on Azure through the marketplace (as described here: https://vimeo.com/183380103) you will need to log into the XG Control Center and perform the update to the latest release version by using the internal up2date mechanism. This will bring your installation to the latest version (MR8).

In addition, I have found this KBA for you: https://community.sophos.com/kb/en-us/125458

For further assistance, please contact your Sophos partner or the Sophos support organization:
https://www.sophos.com/en-us/support.aspx
