### ISSUE TITLE
Micro App Discovery HeadAches2

### ISSUE THREAD

**Issue by zamarax** [sophos-iaas/xg-azure#15]
Because you locked the other thread.

As described in another one of my post's your up2date is broken and doesn't allow you to upgrade to MR8.

**Comment by jpwenzel** [comment]
Dear zamarax,

As mentioned before: please do contact Sophos support with this issue. They'd be happy to help you identifying the source of the upgrade problem and provide you with a solution.

**Comment by zamarax** [comment]
They have, it's a bug in the image your team has published to Azure, it's not something that can be done by the end user but they were able to fix it and get it upgraded after about 6 hours of remote support.

**Comment by jpwenzel** [comment]
Thanks for following up on that one. Would you have a Sophtrac ID so I could have a look at the case? Feel free to ping me/send a personal message if you don't like to include the ID here.

Best,

--JP

**Comment by zamarax** [comment]
#7622408

**Comment by jpwenzel** [comment]
Thanks again for your feedback.

We have identified an issue with our up2date infrastructure and rolled out a fix to the servers. The MR8 up2date package is now again visible for the XG on Azure and instances can be upgraded to the latest version.
